american-dream-league:
    build: .
    ports:
        - 8000:8000
    links:
        - mysql
    environment:
        - DATABASE_USERNAME=root
        - DATABASE_PASSWORD=password
        - DATABASE_HOST=mysql # Use Docker hostname linking
        - DATABASE_PORT=3306
        - DATABASE_NAME=american_dream_league # Database is created by ./database/database.sql
mysql:
    build: ./database
    environment:
        - MYSQL_ROOT_PASSWORD=password
    ports:
        - 3306:3306
